title: "Freiau99"
theme: jekyll-theme-minimal
navbar:
  title: "Freiau99"
  left:
    - text: "Home"
      href: index.html
    - text: "Archiv"
      menu:
        - text: "2024"
          href: archiv-2024.html
        - text: "2023"
          href: archiv-2023.html
        - text: "2022"
          href: archiv-2022.html
        - text: "2021"
          href: archiv-2021.html
        - text: "2020"
          href: archiv-2020.html
    - text: "MHS"
      href: MHS.html
          
